@startuml Sequence-Consume



FileStorage -> QueueEventHandler: 







' Queue: Push queue
' Queue -> QueueStorage: Request to creation queue file
' QueueStorage -> QueueStorage: Create queue file
' QueueStorage -> FileWatcher: Raise event
' FileWatcher -> FileWatcher: Catch event
' FileWatcher -> TaskRouter: Route Task
' FileWatcher -> Client: XXXXXXXXXXXXXX



' Alice -> Bob: Authentication Request
' Bob --> Alice: Authentication Response
' Alice -> Bob: Another authentication Request
' Alice <-- Bob: Another authentication Response
 
@enduml